### ISSUE TITLE
perf: use str.join() replace string addition assignment (+=) for string concatenation

### ISSUE THREAD

**Issue by tobiichi3227** [LifeAdventurer/Moonafly#11]
String concatenation in python have many methods to achieve this.
Such as plus operator (+), addition assignment (+=), f-string, str.join(), etc.
In usually, concatenate multiple strings using str.join() method is an effective way.

I think we can use str.join() in cat command, because cat command might open a large file.
In this case, addition assignment method will allocate more memory to do this, it will increase operation time.

The following is a comparison between small file and large file (using timeit).
| File | Lines | Method | cost time (average of 100 times) |
|-----|-------|------------|--------------------------------------------|
| response_terminal.py | 1191 | += | 0.00915 sec |
| respones_terminal.py | 1191 | str.join() | 0.00156 sec |
| responses.py | 182 | += | 0.00033 sec |
| responses.py | 182 | str.join() | 0.00023 sec |

**Comment by LifeAdventurer** [comment]
It's great that you've explored different string concatenation methods in Python and have considered their efficiency in handling large files. Your comparison between the addition assignment method and the str.join() method using the timeit module provides valuable insights into their performance.

**Comment by LifeAdventurer** [comment]
I assigned this issue to you.

**Comment by LifeAdventurer** [comment]
@tobiichi3227 Can you address this issue since it's been opened by you for a long time?

**Comment by tobiichi3227** [comment]
Ok.
I'm watching anime recently.

**Comment by LifeAdventurer** [comment]
I didn't finish this issue, and I didn't touch it because it was assigned to you at the beginning.

**Comment by tobiichi3227** [comment]
You done.
https://github.com/LifeAdventurer/Moonafly/blob/main/src/split_message.py#L85

**Comment by LifeAdventurer** [comment]
https://github.com/LifeAdventurer/Moonafly/blob/31be4d601ed712ac2b3f0db76e854267f3808c10/src/command/remote.py#L100
https://github.com/LifeAdventurer/Moonafly/blob/31be4d601ed712ac2b3f0db76e854267f3808c10/src/command/game_1A2B.py#L101C1-L107C125
https://github.com/LifeAdventurer/Moonafly/blob/31be4d601ed712ac2b3f0db76e854267f3808c10/src/command/game_1A2B.py#L115C4-L131C21
https://github.com/LifeAdventurer/Moonafly/blob/31be4d601ed712ac2b3f0db76e854267f3808c10/src/terminal_mode.py#L95C1-L101C56

Do you think these parts are fine with using `+=` instead of `str.join`?

**Comment by tobiichi3227** [comment]
In this situation, i don't think change `+=` to `str.join` will bring performance improvement.
